### PR TITLE
Theme annett

### PR DESCRIPTION
**Pull request by annett-djpr**
Function djpr_save_image() is a wrapper function for ggsave. It removes title and subtitle from the last plot and assigns a parameter called 'size', which can be full, threequarter, half and quarter - to fit the DJPR powerpoint template. 

I have tested this and it works. Ready to be merged into the main branch.

### CODE REVIEW

**Comment by MattCowgill** [comment]
Ignore that warning about "conflicting files" that Github is giving us Annett, I'll fix that when it's time to merge the pull request

**Comment by annett-djpr** [comment]
Pulled again, as I need to change threequarters to twothirds.

**Comment by annett-djpr** [comment]
Should be good now to pull back in.

**Review by MattCowgill — APPROVED** [review]
Thanks for your work on this @annett-djpr, all good

**Pull request merged**
